name: Deploy Focus Time App

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: ["master", "develop"]  # Added develop branch
  pull_request:
    branches: ["master", "develop"]  # Added PR checks
  # schedule:
  #   - cron: '0 0 * * *'  # Daily at midnight UTC
  # repository_dispatch:
  #   types: [focus-app-update]

jobs:
  deploy-focus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main site
        uses: actions/checkout@v4
        with:
          path: main-site

      - name: Checkout Focus Time repo
        uses: actions/checkout@v4
        with:
          repository: ameyxd/focus-time
          token: ${{ secrets.GH_PAT }}  # Make sure you have this secret set
          path: focus-time

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install and build Focus Time
        working-directory: focus-time
        run: |
          pnpm install --no-frozen-lockfile
          # Ensure public URL is set correctly
          echo "NEXT_PUBLIC_BASE_PATH=/focus" >> .env.local
          pnpm build

      - name: Debug build output
        working-directory: focus-time
        run: |
          echo "Listing build output contents:"
          ls -la out/

      - name: Copy Focus Time build to main site
        run: |
          rm -rf main-site/public/focus
          mkdir -p main-site/public/focus
          cp -r focus-time/out/* main-site/public/focus/
          # Create a marker file to indicate focus app is deployed
          touch main-site/public/focus/.focus-app-deployed
          echo "Listing focus directory contents:"
          ls -la main-site/public/focus/

      - name: Configure Git
        run: |
          cd main-site
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin
          git checkout project/focus-app
          git pull origin project/focus-app

      - name: Commit and push Focus app changes
        run: |
          cd main-site
          git add public/focus
          git commit -m "Update Focus app build" || echo "No changes to commit"
          git push origin project/focus-app

      - name: Create .nojekyll file
        run: |
          touch main-site/public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./main-site/public/focus
          destination_dir: focus
          keep_files: true

      - name: Verify deployment
        run: |
          echo "Checking if files exist in the correct location..."
          ls -la main-site/public/focus/
          echo "Files will be deployed to: focus/"